import type { HanjaLevel } from '../types';

export const hanjaData: HanjaLevel[] = [
  {
    levelName: 'Sơ cấp',
    levelId: 'beginner',
    chars: [
      {
        char: '人',
        reading: '인',
        meaning: 'Nhân (người)',
        strokeCount: 2,
        radical: '人 (Nhân)',
        examples: [
          { hanja: '本人', hangeul: '본인', romanization: 'bon-in', meaning: 'Bản thân' },
          { hanja: '인기', hangeul: '인기', romanization: 'in-gi', meaning: 'Sự nổi tiếng, được yêu thích' },
          { hanja: '한국인', hangeul: '한국인', romanization: 'han-guk-in', meaning: 'Người Hàn Quốc' },
          { hanja: '외국인', hangeul: '외국인', romanization: 'oe-guk-in', meaning: 'Người nước ngoài' },
          { hanja: '人事', hangeul: '인사', romanization: 'in-sa', meaning: 'Chào hỏi' },
          { hanja: '人生', hangeul: '인생', romanization: 'in-saeng', meaning: 'Cuộc đời, nhân sinh' },
          { hanja: '主人', hangeul: '주인', romanization: 'ju-in', meaning: 'Chủ nhân' },
          { hanja: '인간', hangeul: '인간', romanization: 'in-gan', meaning: 'Con người, nhân loại' },
          { hanja: '인구', hangeul: '인구', romanization: 'in-gu', meaning: 'Dân số, nhân khẩu' },
          { hanja: '개인', hangeul: '개인', romanization: 'gae-in', meaning: 'Cá nhân' },
          { hanja: '인재', hangeul: '인재', romanization: 'in-jae', meaning: 'Nhân tài' },
          { hanja: '미인', hangeul: '미인', romanization: 'mi-in', meaning: 'Mỹ nhân' },
        ],
      },
      {
        char: '大',
        reading: '대',
        meaning: 'Đại (lớn)',
        strokeCount: 3,
        radical: '大 (Đại)',
        examples: [
          { hanja: '大學校', hangeul: '대학교', romanization: 'dae-hak-gyo', meaning: 'Đại học' },
          { hanja: '大門', hangeul: '대문', romanization: 'dae-mun', meaning: 'Cổng chính' },
          { hanja: '대통령', hangeul: '대통령', romanization: 'dae-tong-ryeong', meaning: 'Tổng thống' },
          { hanja: '대부분', hangeul: '대부분', romanization: 'dae-bu-bun', meaning: 'Đại bộ phận, phần lớn' },
          { hanja: '大使館', hangeul: '대사관', romanization: 'dae-sa-gwan', meaning: 'Đại sứ quán' },
          { hanja: '對答', hangeul: '대답', romanization: 'dae-dap', meaning: 'Trả lời' },
          { hanja: '擴大', hangeul: '확대', romanization: 'hwak-dae', meaning: 'Khuếch đại, mở rộng' },
          { hanja: '大衆', hangeul: '대중', romanization: 'dae-jung', meaning: 'Đại chúng' },
          { hanja: '大會', hangeul: '대회', romanization: 'dae-hoe', meaning: 'Đại hội' },
          { hanja: '大企業', hangeul: '대기업', romanization: 'dae-gi-eop', meaning: 'Tập đoàn lớn' },
          { hanja: '最大', hangeul: '최대', romanization: 'choe-dae', meaning: 'Tối đa, lớn nhất' },
          { hanja: '大都市', hangeul: '대도시', romanization: 'dae-do-si', meaning: 'Thành phố lớn' },
        ],
      },
      {
        char: '韓',
        reading: '한',
        meaning: 'Hàn (Hàn Quốc)',
        strokeCount: 18,
        radical: '韋 (Vi)',
        examples: [
          { hanja: '韓國', hangeul: '한국', romanization: 'han-guk', meaning: 'Hàn Quốc' },
          { hanja: '한글', hangeul: '한글', romanization: 'han-geul', meaning: 'Chữ Hangeul' },
          { hanja: '한복', hangeul: '한복', romanization: 'han-bok', meaning: 'Hanbok (trang phục truyền thống)' },
          { hanja: '한식', hangeul: '한식', romanization: 'han-sik', meaning: 'Món ăn Hàn Quốc' },
          { hanja: '大韓民國', hangeul: '대한민국', romanization: 'dae-han-min-guk', meaning: 'Đại Hàn Dân Quốc' },
          { hanja: '韓流', hangeul: '한류', romanization: 'hal-lyu', meaning: 'Làn sóng Hàn (Hallyu)' },
          { hanja: '韓半島', hangeul: '한반도', romanization: 'han-ban-do', meaning: 'Bán đảo Hàn' },
          { hanja: '韓美', hangeul: '한미', romanization: 'han-mi', meaning: 'Hàn-Mỹ' },
          { hanja: '韓日', hangeul: '한일', romanization: 'han-il', meaning: 'Hàn-Nhật' },
          { hanja: '韓醫學', hangeul: '한의학', romanization: 'han-ui-hak', meaning: 'Hàn y học' },
          { hanja: '漢字', hangeul: '한자', romanization: 'han-ja', meaning: 'Chữ Hán' },
          { hanja: '韓牛', hangeul: '한우', romanization: 'han-u', meaning: 'Bò Hàn Quốc' },
        ],
      },
      {
        char: '國',
        reading: '국',
        meaning: 'Quốc (nước)',
        strokeCount: 11,
        radical: '囗 (Vi)',
        examples: [
          { hanja: '국가', hangeul: '국가', romanization: 'guk-ga', meaning: 'Quốc gia' },
          { hanja: '외국인', hangeul: '외국인', romanization: 'oe-guk-in', meaning: 'Người nước ngoài' },
          { hanja: '국민', hangeul: '국민', romanization: 'gung-min', meaning: 'Quốc dân' },
          { hanja: '국내', hangeul: '국내', romanization: 'gung-nae', meaning: 'Trong nước, quốc nội' },
          { hanja: '國際', hangeul: '국제', romanization: 'guk-je', meaning: 'Quốc tế' },
          { hanja: '愛國', hangeul: '애국', romanization: 'ae-guk', meaning: 'Yêu nước' },
          { hanja: '歸國', hangeul: '귀국', romanization: 'gwi-guk', meaning: 'Về nước' },
          { hanja: '國旗', hangeul: '국기', romanization: 'guk-gi', meaning: 'Quốc kỳ' },
          { hanja: '國境', hangeul: '국경', romanization: 'guk-gyeong', meaning: 'Biên giới' },
          { hanja: '愛國歌', hangeul: '애국가', romanization: 'ae-guk-ga', meaning: 'Quốc ca' },
          { hanja: '天國', hangeul: '천국', romanization: 'cheon-guk', meaning: 'Thiên đường' },
          { hanja: '祖國', hangeul: '조국', romanization: 'jo-guk', meaning: 'Tổ quốc' },
        ],
      },
      {
        char: '學',
        reading: '학',
        meaning: 'Học (học tập)',
        strokeCount: 16,
        radical: '子 (Tử)',
        examples: [
          { hanja: '학생', hangeul: '학생', romanization: 'hak-saeng', meaning: 'Học sinh' },
          { hanja: '학교', hangeul: '학교', romanization: 'hak-gyo', meaning: 'Trường học' },
          { hanja: '과학', hangeul: '과학', romanization: 'gwa-hak', meaning: 'Khoa học' },
          { hanja: '유학', hangeul: '유학', romanization: 'yu-hak', meaning: 'Du học' },
          { hanja: '學院', hangeul: '학원', romanization: 'hag-won', meaning: 'Trung tâm học thêm' },
          { hanja: '奬學金', hangeul: '장학금', romanization: 'jang-hak-geum', meaning: 'Học bổng' },
          { hanja: '學期', hangeul: '학기', romanization: 'hak-gi', meaning: 'Học kỳ' },
          { hanja: '학력', hangeul: '학력', romanization: 'hang-nyeok', meaning: 'Học lực' },
          { hanja: '학자', hangeul: '학자', romanization: 'hak-ja', meaning: 'Học giả' },
          { hanja: '독학', hangeul: '독학', romanization: 'dok-hak', meaning: 'Tự học' },
          { hanja: '학비', hangeul: '학비', romanization: 'hak-bi', meaning: 'Học phí' },
          { hanja: '전학', hangeul: '전학', romanization: 'jeon-hak', meaning: 'Chuyển trường' },
        ],
      },
      {
        char: '生',
        reading: '생',
        meaning: 'Sinh (sống, sinh ra)',
        strokeCount: 5,
        radical: '生 (Sinh)',
        examples: [
          { hanja: '생일', hangeul: '생일', romanization: 'saeng-il', meaning: 'Sinh nhật' },
          { hanja: '생활', hangeul: '생활', romanization: 'saeng-hwal', meaning: 'Sinh hoạt, cuộc sống' },
          { hanja: '선생님', hangeul: '선생님', romanization: 'seon-saeng-nim', meaning: 'Giáo viên' },
          { hanja: '평생', hangeul: '평생', romanization: 'pyeong-saeng', meaning: 'Cả đời, bình sinh' },
          { hanja: '發生', hangeul: '발생', romanization: 'bal-saeng', meaning: 'Phát sinh' },
          { hanja: '生産', hangeul: '생산', romanization: 'saeng-san', meaning: 'Sản xuất' },
          { hanja: '生命', hangeul: '생명', romanization: 'saeng-myeong', meaning: 'Sinh mệnh' },
          { hanja: '생선', hangeul: '생선', romanization: 'saeng-seon', meaning: 'Cá tươi' },
          { hanja: '생각', hangeul: '생각', romanization: 'saeng-gak', meaning: 'Suy nghĩ' },
          { hanja: '위생', hangeul: '위생', romanization: 'wi-saeng', meaning: 'Vệ sinh' },
          { hanja: '생방송', hangeul: '생방송', romanization: 'saeng-bang-song', meaning: 'Phát sóng trực tiếp' },
          { hanja: '생물', hangeul: '생물', romanization: 'saeng-mul', meaning: 'Sinh vật' },
        ],
      },
       {
        char: '中',
        reading: '중',
        meaning: 'Trung (giữa, trong)',
        strokeCount: 4,
        radical: '丨 (Cổn)',
        examples: [
          { hanja: '중국', hangeul: '중국', romanization: 'jung-guk', meaning: 'Trung Quốc' },
          { hanja: '회의중', hangeul: '회의중', romanization: 'hoe-ui-jung', meaning: 'Đang họp' },
          { hanja: '중학교', hangeul: '중학교', romanization: 'jung-hak-gyo', meaning: 'Trường trung học cơ sở' },
          { hanja: '중심', hangeul: '중심', romanization: 'jung-sim', meaning: 'Trung tâm' },
          { hanja: '進行中', hangeul: '진행중', romanization: 'jin-haeng-jung', meaning: 'Đang tiến hành' },
          { hanja: '重要', hangeul: '중요', romanization: 'jung-yo', meaning: 'Quan trọng' },
          { hanja: '그中', hangeul: '그중', romanization: 'geu-jung', meaning: 'Trong số đó' },
          { hanja: '集中', hangeul: '집중', romanization: 'jip-jung', meaning: 'Tập trung' },
          { hanja: '中斷', hangeul: '중단', romanization: 'jung-dan', meaning: 'Gián đoạn' },
          { hanja: '中級', hangeul: '중급', romanization: 'jung-geup', meaning: 'Trung cấp' },
          { hanja: '中央', hangeul: '중앙', romanization: 'jung-ang', meaning: 'Trung ương' },
          { hanja: '工事中', hangeul: '공사중', romanization: 'gong-sa-jung', meaning: 'Đang thi công' },
        ],
      },
      {
        char: '小',
        reading: '소',
        meaning: 'Tiểu (nhỏ)',
        strokeCount: 3,
        radical: '小 (Tiểu)',
        examples: [
          { hanja: '소학교', hangeul: '소학교', romanization: 'so-hak-gyo', meaning: 'Trường tiểu học' },
          { hanja: '소설', hangeul: '소설', romanization: 'so-seol', meaning: 'Tiểu thuyết' },
          { hanja: '소심하다', hangeul: '소심하다', romanization: 'so-sim-ha-da', meaning: 'Nhút nhát, rụt rè' },
          { hanja: '소규모', hangeul: '소규모', romanization: 'so-gyu-mo', meaning: 'Quy mô nhỏ' },
          { hanja: '少女', hangeul: '소녀', romanization: 'so-nyeo', meaning: 'Thiếu nữ' },
          { hanja: '小型', hangeul: '소형', romanization: 'so-hyeong', meaning: 'Cỡ nhỏ' },
          { hanja: '縮小', hangeul: '축소', romanization: 'chuk-so', meaning: 'Thu nhỏ' },
          { hanja: '小便', hangeul: '소변', romanization: 'so-byeon', meaning: 'Tiểu tiện' },
          { hanja: '最小', hangeul: '최소', romanization: 'choe-so', meaning: 'Tối thiểu, nhỏ nhất' },
          { hanja: '小人', hangeul: '소인', romanization: 'so-in', meaning: 'Trẻ em (vé)' },
          { hanja: '小包', hangeul: '소포', romanization: 'so-po', meaning: 'Bưu kiện nhỏ' },
          { hanja: '略小하다', hangeul: '약소하다', romanization: 'yak-so-ha-da', meaning: 'Nhỏ bé, tầm thường' },
        ],
      },
      {
        char: '日',
        reading: '일',
        meaning: 'Nhật (ngày, mặt trời, Nhật Bản)',
        strokeCount: 4,
        radical: '日 (Nhật)',
        examples: [
          { hanja: '生日', hangeul: '생일', romanization: 'saeng-il', meaning: 'Sinh nhật' },
          { hanja: '每日', hangeul: '매일', romanization: 'mae-il', meaning: 'Mỗi ngày' },
          { hanja: '日本', hangeul: '일본', romanization: 'il-bon', meaning: 'Nhật Bản' },
          { hanja: '일기', hangeul: '일기', romanization: 'il-gi', meaning: 'Nhật ký' },
          { hanja: '休日', hangeul: '휴일', romanization: 'hyu-il', meaning: 'Ngày nghỉ' },
          { hanja: '作心三日', hangeul: '작심삼일', romanization: 'jak-sim-sam-il', meaning: 'Quyết tâm 3 ngày' },
          { hanja: '日常', hangeul: '일상', romanization: 'il-sang', meaning: 'Thường ngày' },
          { hanja: '日曜日', hangeul: '일요일', romanization: 'ir-yo-il', meaning: 'Chủ Nhật' },
          { hanja: '日光', hangeul: '일광', romanization: 'il-gwang', meaning: 'Ánh nắng mặt trời' },
          { hanja: '日出', hangeul: '일출', romanization: 'il-chul', meaning: 'Mặt trời mọc' },
          { hanja: '平日', hangeul: '평일', romanization: 'pyeong-il', meaning: 'Ngày thường' },
          { hanja: '日程', hangeul: '일정', romanization: 'il-jeong', meaning: 'Lịch trình' },
        ],
      },
      {
        char: '月',
        reading: '월',
        meaning: 'Nguyệt (tháng, mặt trăng)',
        strokeCount: 4,
        radical: '月 (Nguyệt)',
        examples: [
          { hanja: '月曜日', hangeul: '월요일', romanization: 'wor-yo-il', meaning: 'Thứ Hai' },
          { hanja: '每月', hangeul: '매월', romanization: 'mae-wol', meaning: 'Mỗi tháng' },
          { hanja: '一月', hangeul: '일월', romanization: 'ir-wol', meaning: 'Tháng Một' },
          { hanja: '월급', hangeul: '월급', romanization: 'wol-geup', meaning: 'Lương tháng' },
          { hanja: '歲月', hangeul: '세월', romanization: 'se-wol', meaning: 'Năm tháng, thời gian' },
          { hanja: '月貰', hangeul: '월세', romanization: 'wol-se', meaning: 'Tiền thuê nhà hàng tháng' },
          { hanja: '末月', hangeul: '말월', romanization: 'mar-wol', meaning: 'Cuối tháng' },
          { hanja: '月末', hangeul: '월말', romanization: 'wol-mal', meaning: 'Cuối tháng' },
          { hanja: '年月日', hangeul: '연월일', romanization: 'yeon-wor-il', meaning: 'Ngày tháng năm' },
          { hanja: '半月', hangeul: '반달', romanization: 'ban-dal', meaning: 'Bán nguyệt, nửa vầng trăng' },
          { hanja: '月刊', hangeul: '월간', romanization: 'wol-gan', meaning: 'Tạp chí tháng' },
          { hanja: '月初', hangeul: '월초', romanization: 'wol-cho', meaning: 'Đầu tháng' },
        ],
      },
      {
        char: '年',
        reading: '년',
        meaning: 'Niên (năm)',
        strokeCount: 6,
        radical: '干 (Can)',
        examples: [
          { hanja: '昨年', hangeul: '작년', romanization: 'jang-nyeon', meaning: 'Năm ngoái' },
          { hanja: '來年', hangeul: '내년', romanization: 'nae-nyeon', meaning: 'Năm sau' },
          { hanja: '學年', hangeul: '학년', romanization: 'hang-nyeon', meaning: 'Năm học' },
          { hanja: '少年', hangeul: '소년', romanization: 'so-nyeon', meaning: 'Thiếu niên' },
          { hanja: '年歲', hangeul: '연세', romanization: 'yeon-se', meaning: 'Tuổi (kính ngữ)' },
          { hanja: '紀念', hangeul: '기념', romanization: 'gi-nyeom', meaning: 'Kỷ niệm' },
          { hanja: '靑年', hangeul: '청년', romanization: 'cheong-nyeon', meaning: 'Thanh niên' },
          { hanja: '今年', hangeul: '금년', romanization: 'geum-nyeon', meaning: 'Năm nay' },
          { hanja: '年間', hangeul: '연간', romanization: 'yeon-gan', meaning: 'Hàng năm' },
          { hanja: '年度', hangeul: '연도', romanization: 'yeon-do', meaning: 'Năm (học, tài chính)' },
          { hanja: '年代', hangeul: '연대', romanization: 'yeon-dae', meaning: 'Niên đại' },
          { hanja: '中年', hangeul: '중년', romanization: 'jung-nyeon', meaning: 'Trung niên' },
        ],
      },
      {
        char: '火',
        reading: '화',
        meaning: 'Hỏa (lửa)',
        strokeCount: 4,
        radical: '火 (Hỏa)',
        examples: [
          { hanja: '火曜日', hangeul: '화요일', romanization: 'hwa-yo-il', meaning: 'Thứ Ba' },
          { hanja: '火山', hangeul: '화산', romanization: 'hwa-san', meaning: 'Núi lửa' },
          { hanja: '消化器', hangeul: '소화기', romanization: 'so-hwa-gi', meaning: 'Bình chữa cháy' },
          { hanja: '화재', hangeul: '화재', romanization: 'hwa-jae', meaning: 'Hỏa hoạn' },
          { hanja: '火傷', hangeul: '화상', romanization: 'hwa-sang', meaning: 'Vết bỏng' },
          { hanja: '放火', hangeul: '방화', romanization: 'bang-hwa', meaning: 'Phóng hỏa' },
          { hanja: '火力', hangeul: '화력', romanization: 'hwa-ryeok', meaning: 'Hỏa lực' },
          { hanja: '火藥', hangeul: '화약', romanization: 'hwa-yak', meaning: 'Thuốc súng' },
          { hanja: '聖火', hangeul: '성화', romanization: 'seong-hwa', meaning: 'Ngọn đuốc thiêng' },
          { hanja: '火力發電', hangeul: '화력발전', romanization: 'hwa-ryeok-bal-jeon', meaning: 'Nhiệt điện' },
          { hanja: '火病', hangeul: '화병', romanization: 'hwa-byeong', meaning: 'Bệnh Hỏa (bệnh tâm lý)' },
          { hanja: '급화', hangeul: '급화', romanization: 'geup-hwa', meaning: 'Lửa cháy nhanh' },
        ],
      },
      {
        char: '水',
        reading: '수',
        meaning: 'Thủy (nước)',
        strokeCount: 4,
        radical: '水 (Thủy)',
        examples: [
          { hanja: '水曜日', hangeul: '수요일', romanization: 'su-yo-il', meaning: 'Thứ Tư' },
          { hanja: '水泳', hangeul: '수영', romanization: 'su-yeong', meaning: 'Bơi lội' },
          { hanja: '飮料水', hangeul: '음료수', romanization: 'eum-ryo-su', meaning: 'Nước uống' },
          { hanja: '향수', hangeul: '향수', romanization: 'hyang-su', meaning: 'Nước hoa' },
          { hanja: '水道', hangeul: '수도', romanization: 'su-do', meaning: 'Nước máy' },
          { hanja: '洪水', hangeul: '홍수', romanization: 'hong-su', meaning: 'Lũ lụt' },
          { hanja: '海水浴場', hangeul: '해수욕장', romanization: 'hae-su-yok-jang', meaning: 'Bãi tắm biển' },
          { hanja: '水準', hangeul: '수준', romanization: 'su-jun', meaning: 'Tiêu chuẩn, trình độ' },
          { hanja: '浸水', hangeul: '침수', romanization: 'chim-su', meaning: 'Ngập lụt' },
          { hanja: '水産物', hangeul: '수산물', romanization: 'su-san-mul', meaning: 'Thủy sản' },
          { hanja: '水道꼭지', hangeul: '수도꼭지', romanization: 'su-do-kkok-ji', meaning: 'Vòi nước' },
          { hanja: '降水量', hangeul: '강수량', romanization: 'gang-su-ryang', meaning: 'Lượng mưa' },
        ],
      },
      {
        char: '男',
        reading: '남',
        meaning: 'Nam (đàn ông)',
        strokeCount: 7,
        radical: '田 (Điền)',
        examples: [
          { hanja: '男子', hangeul: '남자', romanization: 'nam-ja', meaning: 'Đàn ông, con trai' },
          { hanja: '남동생', hangeul: '남동생', romanization: 'nam-dong-saeng', meaning: 'Em trai' },
          { hanja: '남편', hangeul: '남편', romanization: 'nam-pyeon', meaning: 'Chồng' },
          { hanja: '장남', hangeul: '장남', romanization: 'jang-nam', meaning: 'Trưởng nam' },
          { hanja: '美男', hangeul: '미남', romanization: 'mi-nam', meaning: 'Mỹ nam' },
          { hanja: '男女', hangeul: '남녀', romanization: 'nam-nyeo', meaning: 'Nam nữ' },
          { hanja: '男性', hangeul: '남성', romanization: 'nam-seong', meaning: 'Nam giới' },
          { hanja: '男學生', hangeul: '남학생', romanization: 'nam-hak-saeng', meaning: 'Nam sinh' },
          { hanja: '男性服', hangeul: '남성복', romanization: 'nam-seong-bok', meaning: 'Quần áo nam' },
          { hanja: '次男', hangeul: '차남', romanization: 'cha-nam', meaning: 'Con trai thứ' },
          { hanja: '男女共學', hangeul: '남녀공학', romanization: 'nam-nyeo-gong-hak', meaning: 'Trường học cho cả nam và nữ' },
          { hanja: '長男', hangeul: '장남', romanization: 'jang-nam', meaning: 'Trưởng nam' },
        ],
      },
      {
        char: '女',
        reading: '여',
        meaning: 'Nữ (phụ nữ)',
        strokeCount: 3,
        radical: '女 (Nữ)',
        examples: [
          { hanja: '女子', hangeul: '여자', romanization: 'yeo-ja', meaning: 'Phụ nữ, con gái' },
          { hanja: '여동생', hangeul: '여동생', romanization: 'yeo-dong-saeng', meaning: 'Em gái' },
          { hanja: '少女', hangeul: '소녀', romanization: 'so-nyeo', meaning: 'Thiếu nữ' },
          { hanja: '여왕', hangeul: '여왕', romanization: 'yeo-wang', meaning: 'Nữ hoàng' },
          { hanja: '女子親舊', hangeul: '여자친구', romanization: 'yeo-ja-chin-gu', meaning: 'Bạn gái' },
          { hanja: '女性', hangeul: '여성', romanization: 'yeo-seong', meaning: 'Nữ giới' },
          { hanja: '美女', hangeul: '미녀', romanization: 'mi-nyeo', meaning: 'Mỹ nữ' },
          { hanja: '女學生', hangeul: '여학생', romanization: 'yeo-hak-saeng', meaning: 'Nữ sinh' },
          { hanja: '女俳優', hangeul: '여배우', romanization: 'yeo-bae-u', meaning: 'Nữ diễn viên' },
          { hanja: '長女', hangeul: '장녀', romanization: 'jang-nyeo', meaning: 'Con gái lớn' },
          { hanja: '女性服', hangeul: '여성복', romanization: 'yeo-seong-bok', meaning: 'Quần áo nữ' },
          { hanja: '女神', hangeul: '여신', romanization: 'yeo-sin', meaning: 'Nữ thần' },
        ],
      },
      {
        char: '上',
        reading: '상',
        meaning: 'Thượng (trên)',
        strokeCount: 3,
        radical: '一 (Nhất)',
        examples: [
          { hanja: '세상', hangeul: '세상', romanization: 'se-sang', meaning: 'Thế gian' },
          { hanja: '옥상', hangeul: '옥상', romanization: 'ok-sang', meaning: 'Sân thượng' },
          { hanja: '지상', hangeul: '지상', romanization: 'ji-sang', meaning: 'Trên mặt đất' },
          { hanja: '상사', hangeul: '상사', romanization: 'sang-sa', meaning: 'Cấp trên' },
          { hanja: '上半期', hangeul: '상반기', romanization: 'sang-ban-gi', meaning: 'Nửa đầu năm' },
          { hanja: '上昇', hangeul: '상승', romanization: 'sang-seung', meaning: 'Tăng lên' },
          { hanja: '최상', hangeul: '최상', romanization: 'choe-sang', meaning: 'Tốt nhất, thượng hạng' },
          { hanja: '上級', hangeul: '상급', romanization: 'sang-geup', meaning: 'Cao cấp' },
          { hanja: '起床', hangeul: '기상', romanization: 'gi-sang', meaning: 'Thức dậy' },
          { hanja: '向上', hangeul: '향상', romanization: 'hyang-sang', meaning: 'Nâng cao' },
          { hanja: '上流', hangeul: '상류', romanization: 'sang-ryu', meaning: 'Thượng lưu' },
          { hanja: '上空', hangeul: '상공', romanization: 'sang-gong', meaning: 'Bầu trời, không trung' },
        ],
      },
      {
        char: '下',
        reading: '하',
        meaning: 'Hạ (dưới)',
        strokeCount: 3,
        radical: '一 (Nhất)',
        examples: [
          { hanja: '地下鐵', hangeul: '지하철', romanization: 'ji-ha-cheol', meaning: 'Tàu điện ngầm' },
          { hanja: '天下', hangeul: '천하', romanization: 'cheon-ha', meaning: 'Thiên hạ' },
          { hanja: '하차', hangeul: '하차', romanization: 'ha-cha', meaning: 'Xuống xe' },
          { hanja: '부하', hangeul: '부하', romanization: 'bu-ha', meaning: 'Cấp dưới' },
          { hanja: '下半期', hangeul: '하반기', romanization: 'ha-ban-gi', meaning: 'Nửa cuối năm' },
          { hanja: '下落', hangeul: '하락', romanization: 'ha-rak', meaning: 'Giảm xuống' },
          { hanja: '地下', hangeul: '지하', romanization: 'ji-ha', meaning: 'Dưới lòng đất' },
          { hanja: '下級', hangeul: '하급', romanization: 'ha-geup', meaning: 'Sơ cấp, cấp dưới' },
          { hanja: '以下', hangeul: '이하', romanization: 'i-ha', meaning: 'Dưới, trở xuống' },
          { hanja: '下降', hangeul: '하강', romanization: 'ha-gang', meaning: 'Hạ xuống, giảm xuống' },
          { hanja: '下水道', hangeul: '하수도', romanization: 'ha-su-do', meaning: 'Cống rãnh' },
          { hanja: '年下', hangeul: '연하', romanization: 'yeon-ha', meaning: 'Kém tuổi' },
        ],
      },
      {
        char: '門',
        reading: '문',
        meaning: 'Môn (cửa)',
        strokeCount: 8,
        radical: '門 (Môn)',
        examples: [
          { hanja: '大門', hangeul: '대문', romanization: 'dae-mun', meaning: 'Cổng chính' },
          { hanja: '專門家', hangeul: '전문가', romanization: 'jeon-mun-ga', meaning: 'Chuyên gia' },
          { hanja: '入門', hangeul: '입문', romanization: 'im-mun', meaning: 'Nhập môn' },
          { hanja: '창문', hangeul: '창문', romanization: 'chang-mun', meaning: 'Cửa sổ' },
          { hanja: '訪問', hangeul: '방문', romanization: 'bang-mun', meaning: 'Thăm hỏi, ghé thăm' },
          { hanja: '正門', hangeul: '정문', romanization: 'jeong-mun', meaning: 'Cổng chính' },
          { hanja: '동대문', hangeul: '동대문', romanization: 'dong-dae-mun', meaning: 'Cổng Đông (Dongdaemun)' },
          { hanja: '家門', hangeul: '가문', romanization: 'ga-mun', meaning: 'Gia môn, dòng họ' },
          { hanja: '校門', hangeul: '교문', romanization: 'gyo-mun', meaning: 'Cổng trường' },
          { hanja: '守門', hangeul: '수문', romanization: 'su-mun', meaning: 'Thủ môn' },
          { hanja: '後門', hangeul: '후문', romanization: 'hu-mun', meaning: 'Cổng sau' },
          { hanja: '城門', hangeul: '성문', romanization: 'seong-mun', meaning: 'Cổng thành' },
        ],
      },
    ],
  },
  {
    levelName: 'Trung cấp',
    levelId: 'intermediate',
    chars: [
      {
        char: '語',
        reading: '어',
        meaning: 'Ngữ (ngôn ngữ)',
        strokeCount: 14,
        radical: '言 (Ngôn)',
        examples: [
          { hanja: '韓國語', hangeul: '한국어', romanization: 'han-gug-eo', meaning: 'Tiếng Hàn' },
          { hanja: '外國語', hangeul: '외국어', romanization: 'oe-gug-eo', meaning: 'Ngoại ngữ' },
          { hanja: '英語', hangeul: '영어', romanization: 'yeong-eo', meaning: 'Tiếng Anh' },
          { hanja: '문법', hangeul: '문법', romanization: 'mun-beop', meaning: 'Ngữ pháp' },
          { hanja: '單語', hangeul: '단어', romanization: 'dan-eo', meaning: 'Từ vựng' },
          { hanja: '言語學', hangeul: '언어학', romanization: 'eon-eo-hak', meaning: 'Ngôn ngữ học' },
          { hanja: '母國語', hangeul: '모국어', romanization: 'mo-gug-eo', meaning: 'Tiếng mẹ đẻ' },
          { hanja: '語彙', hangeul: '어휘', romanization: 'eo-hwi', meaning: 'Từ vựng' },
          { hanja: '日本語', hangeul: '일본어', romanization: 'il-bon-eo', meaning: 'Tiếng Nhật' },
          { hanja: '語學堂', hangeul: '어학당', romanization: 'eo-hak-dang', meaning: 'Trung tâm ngôn ngữ' },
          { hanja: '語感', hangeul: '어감', romanization: 'eo-gam', meaning: 'Cảm giác ngôn ngữ' },
          { hanja: '流行語', hangeul: '유행어', romanization: 'yu-haeng-eo', meaning: 'Từ lóng' },
        ],
      },
      {
        char: '話',
        reading: '화',
        meaning: 'Thoại (nói chuyện)',
        strokeCount: 13,
        radical: '言 (Ngôn)',
        examples: [
          { hanja: '對話', hangeul: '대화', romanization: 'dae-hwa', meaning: 'Đối thoại' },
          { hanja: '電話', hangeul: '전화', romanization: 'jeon-hwa', meaning: 'Điện thoại' },
          { hanja: '神話', hangeul: '신화', romanization: 'sin-hwa', meaning: 'Thần thoại' },
          { hanja: '실화', hangeul: '실화', romanization: 'sil-hwa', meaning: 'Chuyện có thật' },
          { hanja: '通話', hangeul: '통화', romanization: 'tong-hwa', meaning: 'Cuộc gọi điện thoại' },
          { hanja: '談話', hangeul: '담화', romanization: 'dam-hwa', meaning: 'Đàm thoại' },
          { hanja: '話題', hangeul: '화제', romanization: 'hwa-je', meaning: 'Chủ đề (câu chuyện)' },
          { hanja: '童話', hangeul: '동화', romanization: 'dong-hwa', meaning: 'Đồng thoại' },
          { hanja: '手話', hangeul: '수화', romanization: 'su-hwa', meaning: 'Ngôn ngữ ký hiệu' },
          { hanja: '秘話', hangeul: '비화', romanization: 'bi-hwa', meaning: 'Chuyện chưa kể' },
          { hanja: '逸話', hangeul: '일화', romanization: 'il-hwa', meaning: 'Giai thoại' },
          { hanja: '國際電話', hangeul: '국제전화', romanization: 'guk-je-jeon-hwa', meaning: 'Điện thoại quốc tế' },
        ],
      },
      {
        char: '食',
        reading: '식',
        meaning: 'Thực (ăn)',
        strokeCount: 9,
        radical: '食 (Thực)',
        examples: [
          { hanja: '食堂', hangeul: '식당', romanization: 'sik-dang', meaning: 'Nhà hàng' },
          { hanja: '飮食', hangeul: '음식', romanization: 'eum-sik', meaning: 'Đồ ăn' },
          { hanja: '間食', hangeul: '간식', romanization: 'gan-sik', meaning: 'Đồ ăn vặt' },
          { hanja: '식사', hangeul: '식사', romanization: 'sik-sa', meaning: 'Bữa ăn' },
          { hanja: '外食', hangeul: '외식', romanization: 'oe-sik', meaning: 'Ăn ngoài' },
          { hanja: '試食', hangeul: '시식', romanization: 'si-sik', meaning: 'Ăn thử' },
          { hanja: '食費', hangeul: '식비', romanization: 'sik-bi', meaning: 'Tiền ăn' },
          { hanja: '食口', hangeul: '식구', romanization: 'sik-gu', meaning: 'Người nhà, miệng ăn' },
          { hanja: '아침食事', hangeul: '아침식사', romanization: 'a-chim-sik-sa', meaning: 'Bữa sáng' },
          { hanja: '食品', hangeul: '식품', romanization: 'sik-pum', meaning: 'Thực phẩm' },
          { hanja: '禁食', hangeul: '금식', romanization: 'geum-sik', meaning: 'Cấm ăn, ăn kiêng' },
          { hanja: '食器', hangeul: '식기', romanization: 'sik-gi', meaning: 'Dụng cụ ăn uống' },
        ],
      },
      {
        char: '飲',
        reading: '음',
        meaning: 'Ẩm (uống)',
        strokeCount: 13,
        radical: '食 (Thực)',
        examples: [
          { hanja: '飮料水', hangeul: '음료수', romanization: 'eum-ryo-su', meaning: 'Nước uống' },
          { hanja: '飮酒', hangeul: '음주', romanization: 'eum-ju', meaning: 'Uống rượu' },
          { hanja: '試飲', hangeul: '시음', romanization: 'si-eum', meaning: 'Uống thử' },
          { hanja: '음용', hangeul: '음용', romanization: 'eum-yong', meaning: 'Việc uống' },
          { hanja: '飮酒運轉', hangeul: '음주운전', romanization: 'eum-ju-un-jeon', meaning: 'Lái xe sau khi uống rượu' },
          { hanja: '過飮', hangeul: '과음', romanization: 'gwa-eum', meaning: 'Uống quá chén' },
          { hanja: '暴飮', hangeul: '폭음', romanization: 'pog-eum', meaning: 'Uống rượu như hũ chìm' },
          { hanja: '飮食', hangeul: '음식', romanization: 'eum-sik', meaning: 'Đồ ăn thức uống' },
          { hanja: '飮料', hangeul: '음료', romanization: 'eum-ryo', meaning: 'Đồ uống' },
          { hanja: '飮酒測定', hangeul: '음주측정', romanization: 'eum-ju-cheuk-jeong', meaning: 'Đo nồng độ cồn' },
          { hanja: '飮用水', hangeul: '음용수', romanization: 'eum-yong-su', meaning: 'Nước uống được' },
          { hanja: '飮酒歌舞', hangeul: '음주가무', romanization: 'eum-ju-ga-mu', meaning: 'Ăn nhậu hát hò' },
        ],
      },
      {
        char: '見',
        reading: '견',
        meaning: 'Kiến (nhìn)',
        strokeCount: 7,
        radical: '見 (Kiến)',
        examples: [
          { hanja: '意見', hangeul: '의견', romanization: 'ui-gyeon', meaning: 'Ý kiến' },
          { hanja: '見學', hangeul: '견학', romanization: 'gyeon-hak', meaning: 'Tham quan học tập' },
          { hanja: '發見', hangeul: '발견', romanization: 'bal-gyeon', meaning: 'Phát hiện, phát kiến' },
          { hanja: '편견', hangeul: '편견', romanization: 'pyeon-gyeon', meaning: 'Thành kiến' },
          { hanja: '百聞不如一見', hangeul: '백문이 불여일견', romanization: 'baek-mun-i bul-yeo-il-gyeon', meaning: 'Trăm nghe không bằng một thấy' },
          { hanja: '豫見', hangeul: '예견', romanization: 'ye-gyeon', meaning: 'Dự đoán, tiên kiến' },
          { hanja: '見解', hangeul: '견해', romanization: 'gyeon-hae', meaning: 'Quan điểm, cách nhìn' },
          { hanja: '見本', hangeul: '견본', romanization: 'gyeon-bon', meaning: 'Hàng mẫu' },
          { hanja: '謁見', hangeul: '알현', romanization: 'al-hyeon', meaning: 'Yết kiến' },
          { hanja: '先入見', hangeul: '선입견', romanization: 'seon-ip-gyeon', meaning: 'Định kiến' },
          { hanja: '再見', hangeul: '재견', romanization: 'jae-gyeon', meaning: 'Gặp lại' },
          { hanja: '參見', hangeul: '참견', romanization: 'cham-gyeon', meaning: 'Xen vào, can thiệp' },
        ],
      },
      {
        char: '聞',
        reading: '문',
        meaning: 'Văn (nghe)',
        strokeCount: 14,
        radical: '耳 (Nhĩ)',
        examples: [
          { hanja: '新聞', hangeul: '신문', romanization: 'sin-mun', meaning: 'Báo' },
          { hanja: '소문', hangeul: '소문', romanization: 'so-mun', meaning: 'Tin đồn' },
          { hanja: '見聞', hangeul: '견문', romanization: 'gyeon-mun', meaning: 'Kiến văn, sự hiểu biết' },
          { hanja: '추문', hangeul: '추문', romanization: 'chu-mun', meaning: 'Scandal, tiếng xấu' },
          { hanja: '聽聞會', hangeul: '청문회', romanization: 'cheong-mun-hoe', meaning: 'Buổi điều trần' },
          { hanja: '傳聞', hangeul: '전문', romanization: 'jeon-mun', meaning: 'Lời đồn, tin đồn' },
          { hanja: '聞一知十', hangeul: '문일지십', romanization: 'mun-il-ji-sip', meaning: 'Nghe một biết mười' },
          { hanja: '聽聞', hangeul: '청문', romanization: 'cheong-mun', meaning: 'Lắng nghe, điều trần' },
          { hanja: '風聞', hangeul: '풍문', romanization: 'pung-mun', meaning: 'Tin đồn, lời đồn' },
          { hanja: '異聞', hangeul: '이문', romanization: 'i-mun', meaning: 'Dị văn, chuyện lạ' },
          { hanja: '前代未聞', hangeul: '전대미문', romanization: 'jeon-dae-mi-mun', meaning: 'Xưa nay chưa từng có' },
          { hanja: '惡聞', hangeul: '악문', romanization: 'ang-mun', meaning: 'Tiếng xấu' },
        ],
      },
      {
        char: '入',
        reading: '입',
        meaning: 'Nhập (vào)',
        strokeCount: 2,
        radical: '入 (Nhập)',
        examples: [
          { hanja: '入口', hangeul: '입구', romanization: 'ip-gu', meaning: 'Lối vào' },
          { hanja: '輸入', hangeul: '수입', romanization: 'su-ip', meaning: 'Nhập khẩu' },
          { hanja: '入場', hangeul: '입장', romanization: 'ip-jang', meaning: 'Vào cửa' },
          { hanja: '입학', hangeul: '입학', romanization: 'ip-hak', meaning: 'Nhập học' },
          { hanja: '入社', hangeul: '입사', romanization: 'ip-sa', meaning: 'Vào công ty' },
          { hanja: '加入', hangeul: '가입', romanization: 'ga-ip', meaning: 'Gia nhập' },
          { hanja: '收入', hangeul: '수입', romanization: 'su-ip', meaning: 'Thu nhập' },
          { hanja: '入院', hangeul: '입원', romanization: 'ib-won', meaning: 'Nhập viện' },
          { hanja: '入國', hangeul: '입국', romanization: 'ip-guk', meaning: 'Nhập cảnh' },
          { hanja: '入金', hangeul: '입금', romanization: 'ip-geum', meaning: 'Gửi tiền vào' },
          { hanja: '進入', hangeul: '진입', romanization: 'jin-ip', meaning: 'Đi vào, tiến vào' },
          { hanja: '入隊', hangeul: '입대', romanization: 'ip-dae', meaning: 'Nhập ngũ' },
        ],
      },
      {
        char: '出',
        reading: '출',
        meaning: 'Xuất (ra)',
        strokeCount: 5,
        radical: '凵 (Khảm)',
        examples: [
          { hanja: '出口', hangeul: '출구', romanization: 'chul-gu', meaning: 'Lối ra' },
          { hanja: '輸出', hangeul: '수출', romanization: 'su-chul', meaning: 'Xuất khẩu' },
          { hanja: '外出', hangeul: '외출', romanization: 'oe-chul', meaning: 'Đi ra ngoài' },
          { hanja: '출발', hangeul: '출발', romanization: 'chul-bal', meaning: 'Xuất phát' },
          { hanja: '出張', hangeul: '출장', romanization: 'chul-jang', meaning: 'Đi công tác' },
          { hanja: '出勤', hangeul: '출근', romanization: 'chul-geun', meaning: 'Đi làm' },
          { hanja: '出國', hangeul: '출국', romanization: 'chul-guk', meaning: 'Xuất cảnh' },
          { hanja: '出席', hangeul: '출석', romanization: 'chul-seok', meaning: 'Có mặt, điểm danh' },
          { hanja: '出版', hangeul: '출판', romanization: 'chul-pan', meaning: 'Xuất bản' },
          { hanja: '退出', hangeul: '퇴출', romanization: 'toe-chul', meaning: 'Rút lui, bị loại' },
          { hanja: '出生', hangeul: '출생', romanization: 'chul-saeng', meaning: 'Ra đời' },
          { hanja: '出演', hangeul: '출연', romanization: 'chul-yeon', meaning: 'Diễn xuất' },
        ],
      },
      {
        char: '東',
        reading: '동',
        meaning: 'Đông (phía đông)',
        strokeCount: 8,
        radical: '木 (Mộc)',
        examples: [
          { hanja: '동쪽', hangeul: '동쪽', romanization: 'dong-jjok', meaning: 'Phía Đông' },
          { hanja: '동대문', hangeul: '동대문', romanization: 'dong-dae-mun', meaning: 'Cổng phía Đông' },
          { hanja: '동해', hangeul: '동해', romanization: 'dong-hae', meaning: 'Biển Đông' },
          { hanja: '동남아', hangeul: '동남아', romanization: 'dong-nam-a', meaning: 'Đông Nam Á' },
          { hanja: '동문서답', hangeul: '동문서답', romanization: 'dong-mun-seo-dap', meaning: 'Hỏi đông đáp tây' },
          { hanja: '동양', hangeul: '동양', romanization: 'dong-yang', meaning: 'Đông phương' },
          { hanja: '東部', hangeul: '동부', romanization: 'dong-bu', meaning: 'Miền Đông' },
          { hanja: '東風', hangeul: '동풍', romanization: 'dong-pung', meaning: 'Gió Đông' },
          { hanja: '東西南北', hangeul: '동서남북', romanization: 'dong-seo-nam-buk', meaning: 'Đông Tây Nam Bắc' },
          { hanja: '極東', hangeul: '극동', romanization: 'geuk-dong', meaning: 'Cực Đông' },
          { hanja: '關東', hangeul: '관동', romanization: 'gwan-dong', meaning: 'Vùng Gwandong' },
          { hanja: '東京', hangeul: '동경', romanization: 'dong-gyeong', meaning: 'Tokyo' },
        ],
      },
       {
        char: '西',
        reading: '서',
        meaning: 'Tây (phía tây)',
        strokeCount: 6,
        radical: '西 (Tây)',
        examples: [
          { hanja: '서쪽', hangeul: '서쪽', romanization: 'seo-jjok', meaning: 'Phía Tây' },
          { hanja: '서양', hangeul: '서양', romanization: 'seo-yang', meaning: 'Tây phương' },
          { hanja: '서해', hangeul: '서해', romanization: 'seo-hae', meaning: 'Biển Tây (Biển Hoàng Hải)' },
          { hanja: '西洋人', hangeul: '서양인', romanization: 'seo-yang-in', meaning: 'Người phương Tây' },
          { hanja: '大西洋', hangeul: '대서양', romanization: 'dae-seo-yang', meaning: 'Đại Tây Dương' },
          { hanja: '西歐', hangeul: '서구', romanization: 'seo-gu', meaning: 'Tây Âu' },
          { hanja: '西部', hangeul: '서부', romanization: 'seo-bu', meaning: 'Miền Tây' },
          { hanja: '西風', hangeul: '서풍', romanization: 'seo-pung', meaning: 'Gió Tây' },
          { hanja: '西大門', hangeul: '서대문', romanization: 'seo-dae-mun', meaning: 'Cổng Tây' },
          { hanja: '西半球', hangeul: '서반구', romanization: 'seo-ban-gu', meaning: 'Tây bán cầu' },
          { hanja: '東西', hangeul: '동서', romanization: 'dong-seo', meaning: 'Đông Tây' },
          { hanja: '華西', hangeul: '화서', romanization: 'hwa-seo', meaning: 'Hwaseo (địa danh)' },
        ],
      },
      {
        char: '南',
        reading: '남',
        meaning: 'Nam (phía nam)',
        strokeCount: 9,
        radical: '十 (Thập)',
        examples: [
          { hanja: '남쪽', hangeul: '남쪽', romanization: 'nam-jjok', meaning: 'Phía Nam' },
          { hanja: '남대문', hangeul: '남대문', romanization: 'nam-dae-mun', meaning: 'Cổng phía Nam' },
          { hanja: '江南', hangeul: '강남', romanization: 'gang-nam', meaning: 'Gangnam (phía Nam sông)' },
          { hanja: '남북', hangeul: '남북', romanization: 'nam-buk', meaning: 'Nam-Bắc' },
          { hanja: '越南', hangeul: '베트남', romanization: 'be-teu-nam', meaning: 'Việt Nam' },
          { hanja: '동남아', hangeul: '동남아', romanization: 'dong-nam-a', meaning: 'Đông Nam Á' },
          { hanja: '南部', hangeul: '남부', romanization: 'nam-bu', meaning: 'Miền Nam' },
          { hanja: '南風', hangeul: '남풍', romanization: 'nam-pung', meaning: 'Gió Nam' },
          { hanja: '南美', hangeul: '남미', romanization: 'nam-mi', meaning: 'Nam Mỹ' },
          { hanja: '南極', hangeul: '남극', romanization: 'nam-geuk', meaning: 'Nam Cực' },
          { hanja: '越南', hangeul: '월남', romanization: 'wol-nam', meaning: 'Việt Nam (cách gọi cũ)' },
          { hanja: '南山', hangeul: '남산', romanization: 'nam-san', meaning: 'Núi Namsan' },
        ],
      },
      {
        char: '北',
        reading: '북',
        meaning: 'Bắc (phía bắc)',
        strokeCount: 5,
        radical: '匕 (Chủy)',
        examples: [
          { hanja: '북쪽', hangeul: '북쪽', romanization: 'buk-jjok', meaning: 'Phía Bắc' },
          { hanja: '북한', hangeul: '북한', romanization: 'buk-han', meaning: 'Bắc Hàn (Triều Tiên)' },
          { hanja: '강북', hangeul: '강북', romanization: 'gang-buk', meaning: 'Gangbuk (phía Bắc sông)' },
          { hanja: '패배', hangeul: '패배', romanization: 'pae-bae', meaning: 'Thất bại (Bại Bắc)' },
          { hanja: '북상', hangeul: '북상', romanization: 'buk-sang', meaning: 'Đi lên phía Bắc' },
          { hanja: '남북', hangeul: '남북', romanization: 'nam-buk', meaning: 'Nam-Bắc' },
          { hanja: '北部', hangeul: '북부', romanization: 'buk-bu', meaning: 'Miền Bắc' },
          { hanja: '北風', hangeul: '북풍', romanization: 'buk-pung', meaning: 'Gió Bắc' },
          { hanja: '北美', hangeul: '북미', romanization: 'bung-mi', meaning: 'Bắc Mỹ' },
          { hanja: '北極', hangeul: '북극', romanization: 'buk-geuk', meaning: 'Bắc Cực' },
          { hanja: '脫北', hangeul: '탈북', romanization: 'tal-buk', meaning: 'Đào thoát khỏi Triều Tiên' },
          { hanja: '北京', hangeul: '북경', romanization: 'buk-gyeong', meaning: 'Bắc Kinh' },
        ],
      },
    ],
  },
  {
    levelName: 'Cao cấp',
    levelId: 'advanced',
    chars: [
      {
        char: '心',
        reading: '심',
        meaning: 'Tâm (trái tim, tấm lòng)',
        strokeCount: 4,
        radical: '心 (Tâm)',
        examples: [
          { hanja: '心臟', hangeul: '심장', romanization: 'sim-jang', meaning: 'Trái tim (cơ quan)' },
          { hanja: '中心', hangeul: '중심', romanization: 'jung-sim', meaning: 'Trung tâm' },
          { hanja: '관심', hangeul: '관심', romanization: 'gwan-sim', meaning: 'Sự quan tâm' },
          { hanja: '安心', hangeul: '안심', romanization: 'an-sim', meaning: 'An tâm' },
          { hanja: '心理學', hangeul: '심리학', romanization: 'sim-ri-hak', meaning: 'Tâm lý học' },
          { hanja: '決心', hangeul: '결심', romanization: 'gyeol-sim', meaning: 'Quyết tâm' },
          { hanja: '자존심', hangeul: '자존심', romanization: 'ja-jon-sim', meaning: 'Lòng tự trọng' },
          { hanja: '深刻하다', hangeul: '심각하다', romanization: 'sim-gak-ha-da', meaning: 'Nghiêm trọng' },
          { hanja: '熱心', hangeul: '열심', romanization: 'yeol-sim', meaning: 'Nhiệt tâm, chăm chỉ' },
          { hanja: '好奇心', hangeul: '호기심', romanization: 'ho-gi-sim', meaning: 'Lòng hiếu kỳ' },
          { hanja: '心理', hangeul: '심리', romanization: 'sim-ri', meaning: 'Tâm lý' },
          { hanja: '良心', hangeul: '양심', romanization: 'yang-sim', meaning: 'Lương tâm' },
        ],
      },
      {
        char: '身',
        reading: '신',
        meaning: 'Thân (cơ thể)',
        strokeCount: 7,
        radical: '身 (Thân)',
        examples: [
          { hanja: '身體', hangeul: '신체', romanization: 'sin-che', meaning: 'Thân thể' },
          { hanja: '自身', hangeul: '자신', romanization: 'ja-sin', meaning: 'Tự thân, bản thân' },
          { hanja: '出身', hangeul: '출신', romanization: 'chul-sin', meaning: 'Xuất thân' },
          { hanja: '정신', hangeul: '정신', romanization: 'jeong-sin', meaning: 'Tinh thần' },
          { hanja: '身分證', hangeul: '신분증', romanization: 'sin-bun-jjeung', meaning: 'Chứng minh thư' },
          { hanja: '全身', hangeul: '전신', romanization: 'jeon-sin', meaning: 'Toàn thân' },
          { hanja: '獨身', hangeul: '독신', romanization: 'dok-sin', meaning: 'Độc thân' },
          { hanja: '身長', hangeul: '신장', romanization: 'sin-jang', meaning: 'Chiều cao' },
          { hanja: '身分', hangeul: '신분', romanization: 'sin-bun', meaning: 'Thân phận' },
          { hanja: '妊娠', hangeul: '임신', romanization: 'im-sin', meaning: 'Mang thai' },
          { hanja: '肉身', hangeul: '육신', romanization: 'yuk-sin', meaning: 'Thể xác' },
          { hanja: '變身', hangeul: '변신', romanization: 'byeon-sin', meaning: 'Biến thân, thay đổi' },
        ],
      },
      {
        char: '安',
        reading: '안',
        meaning: 'An (yên bình)',
        strokeCount: 6,
        radical: '宀 (Miên)',
        examples: [
          { hanja: '安全', hangeul: '안전', romanization: 'an-jeon', meaning: 'An toàn' },
          { hanja: '安心', hangeul: '안심', romanization: 'an-sim', meaning: 'An tâm' },
          { hanja: '불안', hangeul: '불안', romanization: 'bur-an', meaning: 'Bất an' },
          { hanja: '안내', hangeul: '안내', romanization: 'an-nae', meaning: 'Hướng dẫn (An Nội)' },
          { hanja: '安否', hangeul: '안부', romanization: 'an-bu', meaning: 'Lời hỏi thăm sức khỏe' },
          { hanja: '安定', hangeul: '안정', romanization: 'an-jeong', meaning: 'Ổn định' },
          { hanja: '治安', hangeul: '치안', romanization: 'chi-an', meaning: 'Trị an' },
          { hanja: '便安', hangeul: '편안', romanization: 'pyeon-an', meaning: 'Thoải mái, bình an' },
          { hanja: '安定感', hangeul: '안정감', romanization: 'an-jeong-gam', meaning: 'Cảm giác ổn định' },
          { hanja: '安寧', hangeul: '안녕', romanization: 'an-nyeong', meaning: 'Bình an' },
          { hanja: '安全벨트', hangeul: '안전벨트', romanization: 'an-jeon-bel-teu', meaning: 'Dây an toàn' },
          { hanja: '安保', hangeul: '안보', romanization: 'an-bo', meaning: 'An ninh' },
        ],
      },
      {
        char: '不',
        reading: '불',
        meaning: 'Bất (không)',
        strokeCount: 4,
        radical: '一 (Nhất)',
        examples: [
          { hanja: '不安', hangeul: '불안', romanization: 'bur-an', meaning: 'Bất an' },
          { hanja: '不便', hangeul: '불편', romanization: 'bul-pyeon', meaning: 'Bất tiện' },
          { hanja: '不可能', hangeul: '불가능', romanization: 'bul-ga-neung', meaning: 'Bất khả năng, không thể' },
          { hanja: '부동산', hangeul: '부동산', romanization: 'bu-dong-san', meaning: 'Bất động sản' },
          { hanja: '不足', hangeul: '부족', romanization: 'bu-jok', meaning: 'Thiếu, bất túc' },
          { hanja: '不當', hangeul: '부당', romanization: 'bu-dang', meaning: 'Không chính đáng' },
          { hanja: '不幸', hangeul: '불행', romanization: 'bul-haeng', meaning: 'Bất hạnh' },
          { hanja: '不滿', hangeul: '불만', romanization: 'bul-man', meaning: 'Bất mãn' },
          { hanja: '不法', hangeul: '불법', romanization: 'bul-beop', meaning: 'Bất hợp pháp' },
          { hanja: '不足하다', hangeul: '부족하다', romanization: 'bu-jok-ha-da', meaning: 'Thiếu' },
          { hanja: '不快', hangeul: '불쾌', romanization: 'bul-kwae', meaning: 'Khó chịu' },
          { hanja: '不注意', hangeul: '부주의', romanization: 'bu-ju-ui', meaning: 'Bất cẩn' },
        ],
        notes: 'Khi đứng trước ㅎ hoặc ㄷ, đọc là 부 (bu).'
      },
      {
        char: '愛',
        reading: '애',
        meaning: 'Ái (yêu)',
        strokeCount: 13,
        radical: '心 (Tâm)',
        examples: [
          { hanja: '愛情', hangeul: '애정', romanization: 'ae-jeong', meaning: 'Ái tình' },
          { hanja: '애인', hangeul: '애인', romanization: 'ae-in', meaning: 'Người yêu' },
          { hanja: '동료애', hangeul: '동료애', romanization: 'dong-ryo-ae', meaning: 'Tình đồng nghiệp' },
          { hanja: '愛國心', hangeul: '애국심', romanization: 'ae-guk-sim', meaning: 'Lòng yêu nước' },
          { hanja: '愛玩動物', hangeul: '애완동물', romanization: 'ae-wan-dong-mul', meaning: 'Thú cưng' },
          { hanja: '戀愛', hangeul: '연애', romanization: 'yeon-ae', meaning: 'Yêu đương' },
          { hanja: '愛着', hangeul: '애착', romanization: 'ae-chak', meaning: 'Lưu luyến, quyến luyến' },
          { hanja: '愛用', hangeul: '애용', romanization: 'ae-yong', meaning: 'Ưa dùng, tin dùng' },
          { hanja: '友愛', hangeul: '우애', romanization: 'u-ae', meaning: 'Tình bạn' },
          { hanja: '愛讀者', hangeul: '애독자', romanization: 'ae-dok-ja', meaning: 'Độc giả yêu thích' },
          { hanja: '愛國', hangeul: '애국', romanization: 'ae-guk', meaning: 'Yêu nước' },
          { hanja: '人類愛', hangeul: '인류애', romanization: 'il-lyu-ae', meaning: 'Tình yêu nhân loại' },
        ],
      },
      {
        char: '家',
        reading: '가',
        meaning: 'Gia (nhà)',
        strokeCount: 10,
        radical: '宀 (Miên)',
        examples: [
          { hanja: '가족', hangeul: '가족', romanization: 'ga-jok', meaning: 'Gia đình' },
          { hanja: '전문가', hangeul: '전문가', romanization: 'jeon-mun-ga', meaning: 'Chuyên gia' },
          { hanja: '가구', hangeul: '가구', romanization: 'ga-gu', meaning: 'Đồ gia dụng' },
          { hanja: '家庭', hangeul: '가정', romanization: 'ga-jeong', meaning: 'Gia đình (family unit)' },
          { hanja: '家事', hangeul: '가사', romanization: 'ga-sa', meaning: 'Việc nhà' },
          { hanja: '歸家', hangeul: '귀가', romanization: 'gwi-ga', meaning: 'Về nhà' },
          { hanja: '家長', hangeul: '가장', romanization: 'ga-jang', meaning: 'Gia trưởng' },
          { hanja: '國家', hangeul: '국가', romanization: 'guk-ga', meaning: 'Quốc gia' },
          { hanja: '大家族', hangeul: '대가족', romanization: 'dae-ga-jok', meaning: 'Đại gia đình' },
          { hanja: '家出', hangeul: '가출', romanization: 'ga-chul', meaning: 'Bỏ nhà ra đi' },
          { hanja: '作家', hangeul: '작가', romanization: 'jak-ga', meaning: 'Tác gia, nhà văn' },
          { hanja: '畫家', hangeul: '화가', romanization: 'hwa-ga', meaning: 'Họa sĩ' },
        ],
      },
       {
        char: '言',
        reading: '언',
        meaning: 'Ngôn (lời nói)',
        strokeCount: 7,
        radical: '言 (Ngôn)',
        examples: [
          { hanja: '언어', hangeul: '언어', romanization: 'eon-eo', meaning: 'Ngôn ngữ' },
          { hanja: '증언', hangeul: '증언', romanization: 'jeung-eon', meaning: 'Lời làm chứng' },
          { hanja: '유언', hangeul: '유언', romanization: 'yu-eon', meaning: 'Di ngôn' },
          { hanja: '언론', hangeul: '언론', romanization: 'eol-lon', meaning: 'Ngôn luận, báo chí' },
          { hanja: '방언', hangeul: '방언', romanization: 'bang-eon', meaning: 'Phương ngữ' },
          { hanja: '무언', hangeul: '무언', romanization: 'mu-eon', meaning: 'Im lặng, vô ngôn' },
          { hanja: '言行', hangeul: '언행', romanization: 'eon-haeng', meaning: 'Lời nói và hành động' },
          { hanja: '宣言', hangeul: '선언', romanization: 'seon-eon', meaning: 'Tuyên ngôn' },
          { hanja: '豫言', hangeul: '예언', romanization: 'ye-eon', meaning: 'Tiên đoán' },
          { hanja: '助言', hangeul: '조언', romanization: 'jo-eon', meaning: 'Lời khuyên' },
          { hanja: '食言', hangeul: '식언', romanization: 'sig-eon', meaning: 'Nuốt lời' },
          { hanja: '言及', hangeul: '언급', romanization: 'eon-geup', meaning: 'Đề cập' },
        ],
      },
      {
        char: '事',
        reading: '사',
        meaning: 'Sự (việc)',
        strokeCount: 8,
        radical: '亅 (Quyết)',
        examples: [
          { hanja: '食事', hangeul: '식사', romanization: 'sik-sa', meaning: 'Bữa ăn' },
          { hanja: '事件', hangeul: '사건', romanization: 'sa-geon', meaning: 'Sự kiện, vụ việc' },
          { hanja: '無事', hangeul: '무사', romanization: 'mu-sa', meaning: 'Vô sự, bình an' },
          { hanja: '事務室', hangeul: '사무실', romanization: 'sa-mu-sil', meaning: 'Văn phòng' },
          { hanja: '行事', hangeul: '행사', romanization: 'haeng-sa', meaning: 'Sự kiện' },
          { hanja: '事業', hangeul: '사업', romanization: 'sa-eop', meaning: 'Kinh doanh, sự nghiệp' },
          { hanja: '事實', hangeul: '사실', romanization: 'sa-sil', meaning: 'Sự thật' },
          { hanja: '事故', hangeul: '사고', romanization: 'sa-go', meaning: 'Tai nạn, sự cố' },
          { hanja: '人事', hangeul: '인사', romanization: 'in-sa', meaning: 'Nhân sự' },
          { hanja: '事情', hangeul: '사정', romanization: 'sa-jeong', meaning: 'Tình hình, sự tình' },
          { hanja: '判事', hangeul: '판사', romanization: 'pan-sa', meaning: 'Thẩm phán' },
          { hanja: '工事', hangeul: '공사', romanization: 'gong-sa', meaning: 'Công trình' },
        ],
      },
    ],
  }
];
